### ISSUE TITLE
no web support

### ISSUE THREAD

**Issue by sjy110** [turkialawlqy/string_encryption#2]
hi, based on the packages description on pub.dev, it support web. but when i got this error when running on web..

Error: PlatformException(Unimplemented, null, string_encryption for web doesn't implement 'encrypt', null)
    at Object.throw_ [as throw] (http://localhost:61608/dart_sdk.js:5348:11)
at StandardMethodCodec.decodeEnvelope (http://localhost:61608/packages/flutter/src/services/system_channels.dart.lib.js:799:19)
at MethodChannel._invokeMethod (http://localhost:61608/packages/flutter/src/services/system_channels.dart.lib.js:964:47)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61608/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:61608/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:61608/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:61608/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:61608/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:61608/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61608/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:61608/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:61608/dart_sdk.js:39380:13)
    at http://localhost:61608/dart_sdk.js:34887:9

pls help thanks...

**Comment by redDwarf03** [comment]
with web version, I have this issue for my own:
```
Error: MissingPluginException(No implementation found for method generate_salt on channel string_encryption)
    at Object.throw_ [as throw] (http://localhost:50899/dart_sdk.js:5061:11)
    at MethodChannel._invokeMethod (http://localhost:50899/packages/flutter/src/services/restoration.dart.lib.js:1526:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50899/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:50899/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50899/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:50899/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:50899/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:50899/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50899/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:50899/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:50899/dart_sdk.js:38784:13)
    at http://localhost:50899/dart_sdk.js:34519:9
```

**Comment by redDwarf03** [comment]
@sjy110 what version of the lib do you use please

**Comment by sjy110** [comment]
hi, I'm using the latest version of this package

**Comment by redDwarf03** [comment]
ok. i have some issue with 2.0.5 (cf https://github.com/turkialawlqy/string_encryption/issues/1)

For info, I replace string_encryption lib for the moment for web platform with this code:
(the advantage: it works for all platform and it's the same code for android or iOS unlike Kotlin code and swift)

```
import 'package:crypto/crypto.dart';
import 'package:encrypt/encrypt.dart';
import 'package:tuple/tuple.dart';

Uint8List genRandomWithNonZero(int seedLength) {
  final random = Random.secure();
  const int randomMax = 245;
  final Uint8List uint8list = Uint8List(seedLength);
  for (int i = 0; i < seedLength; i++) {
    uint8list[i] = random.nextInt(randomMax) + 1;
  }
  return uint8list;
}

Uint8List createUint8ListFromString(String s) {
  var ret = new Uint8List(s.length);
  for (var i = 0; i < s.length; i++) {
    ret[i] = s.codeUnitAt(i);
  }
  return ret;
}

Tuple2<Uint8List, Uint8List> deriveKeyAndIV(String passphrase, Uint8List salt) {
  var password = createUint8ListFromString(passphrase);
  Uint8List concatenatedHashes = Uint8List(0);
  Uint8List currentHash = Uint8List(0);
  bool enoughBytesForKey = false;
  Uint8List preHash = Uint8List(0);

  while (!enoughBytesForKey) {
    if (currentHash.length > 0)
      preHash = Uint8List.fromList(currentHash + password + salt);
    else
      preHash = Uint8List.fromList(password + salt);

    currentHash = Uint8List.fromList(md5.convert(preHash).bytes);
    concatenatedHashes = Uint8List.fromList(concatenatedHashes + currentHash);
    if (concatenatedHashes.length >= 48) enoughBytesForKey = true;
  }

  var keyBtyes = concatenatedHashes.sublist(0, 32);
  var ivBtyes = concatenatedHashes.sublist(32, 48);
  return new Tuple2(keyBtyes, ivBtyes);
}
```

Encrypt method:
```
  final salt = genRandomWithNonZero(8);
  var keyndIV = deriveKeyAndIV(password, salt);
  final key = Key(keyndIV.item1);
  final iv = IV(keyndIV.item2);
  final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: "PKCS7"));
  final encrypted = encrypter.encrypt(HEX.encode(privKey), iv: iv);
  Uint8List encryptedBytesWithSalt = Uint8List.fromList(
      createUint8ListFromString("Salted__") + salt + encrypted.bytes);
  String encrypted = base64.encode(encryptedBytesWithSalt);
```

Decrypt method:
```
  final String? encryptedPrivKey = encrypted;
  Uint8List encryptedBytesWithSalt = base64.decode(encryptedPrivKey!);
  Uint8List encryptedBytes =
      encryptedBytesWithSalt.sublist(16, encryptedBytesWithSalt.length);
  final salt = encryptedBytesWithSalt.sublist(8, 16);
  var keyndIV = deriveKeyAndIV(password, salt);
  final key = Key(keyndIV.item1);
  final iv = IV(keyndIV.item2);
  final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: "PKCS7"));
  final decrypted = encrypter.decrypt64(base64.encode(encryptedBytes), iv: iv);
  
```

**Comment by sjy110** [comment]
wow thanks for the help man, appreciated...

**Comment by redDwarf03** [comment]
no pb.
warning: the result is not exactly similar with string_encryption but I think It's secure. please, if you can, tell me if you think if the security of this algo is acceptable :)

**Comment by redDwarf03** [comment]
@sjy110 , have you tested my solution ?
